# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm'

    - name: Install dependencies and build
      run: |
        npm install
        # npm fund
        # npm audit fix --force
        npm run build:prod

    - name: Create zip archive of dist folder
      id: zip
      run: |
        cd dist
        zip -r ../${{ matrix.node-version }}-headscale-panel-ui.zip .  # 假设需要将dist文件夹内容压缩为headscale-panel-ui.zip
        echo "status=success" >> "$GITHUB_OUTPUT"


    - name: Create Release Tag
      id: tag
      # if: steps.zip.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H")" >> "$GITHUB_OUTPUT"
        touch release.txt
        echo "
        编译release " >> release.txt
        echo "status=success" >> "$GITHUB_OUTPUT"

    - name: Push to Releases
      uses: softprops/action-gh-release@v1
      # if: steps.tag.outputs.status == 'success' && !cancelled()
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ matrix.node-version }}-headscale-panel-ui.zip

    - name: 上传至artifact
      uses: actions/upload-artifact@main
      # if: steps.zip.output.status == 'success' && !cancelled()
      with:
        name: ${{ matrix.node-version }}-headscale-panel-ui
        path: ${{ matrix.node-version }}-headscale-panel-ui.zip
