# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]  # 触发条件是release被创建

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm'

    - name: Install dependencies and build
      run: |
        npm install
        # npm fund
        # npm audit fix --force
        npm run build:prod

    

    - name: Create zip archive of dist folder
      id: zip
      run: |
        cd dist
        zip -r ../headscale-panel-ui.zip .  # 假设需要将dist文件夹内容压缩为headscale-panel-ui.zip
        ls

    - name: Create Release Asset
      id: create_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}  # 确保这里是从事件对象正确获取upload_url
        asset_path: ./headscale-panel-ui.zip
        asset_name: headscale-panel-ui.zip
        asset_content_type: application/zip

    - name: 上传至artifact
      uses: actions/upload-artifact@main
      # if: steps.zip.outputs.status == 'success'
      with:
        name: ${{ matrix.node-version }}-headscale-panel-ui
        path: headscale-panel-ui.zip
